### ISSUE TITLE
Proposal: Page Level Upgrade

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#439]
**Proposal:** an upgrade file for _page_ data, not just component data.

**Reason:** we treat components as a data structured that can be iterated on, but we don't allow the same for pages.

**Question:** is this really a useful tool though? I don't know if it's worth providing or if this is something that's better to be run externally.

**Use Cases:**
- Swapping layouts based on page data
- Re-mapping page areas
- Removing/Adding components to page areas

**Comment by nelsonpecora** [comment]
Hmm! This might actually be useful, but how would we implement it? (Where would the file(s) live, and what kinds of pages would be hit by an upgrade? All pages? `sites/upgrade.js`?

**Comment by jonwinton** [comment]
Ohhh I like that idea of scoping it to a site! That could be handy. 

But yes, all pages. You would have to test in the upgrade if you wanted to actually upgrade based on the content.

The hard part would be ordering. We resolve from the page level down, so what happens if you upgrade a page to, say, change all component refs to `.../_components/...`? Would we resolve all the components normally, let THEIR upgrades run and then run the page level one? 

It's an extreme use case, but it technically could make moving between large breaking versions of Amphora possible.

**Comment by pfeytser** [comment]
Focus on better tooling first, if that doesn't solve it, then revisit this.

**Comment by nelsonpecora** [comment]
We have another use case for this! Adding a meta component (in this case, AMP) to a bunch of pages.

**Comment by zonika** [comment]
Another use case comes with the article redesign, where we'd ideally like to do a few things that would require a page level upgrade (or just a script, but I know we want to move away from that solution)

1. I'd love to get to a point where feature ledes live inside article components. Unfortunately, because articles and feature ledes exist on the same level in page data, they aren't aware of each other, so there wouldn't be a way to absorb feature lede data into article data without an upgrade that happens on the page level.
2. The other use case is the fact that we're likely going to change (read: streamline) the layouts being used on article pages. This will likely mean that layout refs on pages would need to be updated, some way or another

**Comment by nelsonpecora** [comment]
* function signature is (uri, data, locals)
* object with `{ '1.0': fn }` passed into amphora as `pageUpgrades` on server start
* page upgrades happen on the GET, same as components
* current page version is determined by parsing the `pageUpgrades` object

**Comment by pfeytser** [comment]
Ice-boxing until Amphora v7

**Comment by cruzanmo** [comment]
This would be useful for adding an analytics component to all page instances.

**Comment by TTaitFoster** [comment]
This can be achieved via database migration due to the move to postgres.
