### ISSUE TITLE
Component Can 404 a Page

### ISSUE THREAD

**Issue by pfeytser** [clay/amphora#466]
Go here: http://nymag.com/daily/intelligencer/?start=90000

There aren't 90k DI articles yet the page renders when it should 404.

Proposal: Amphora hook passed in the `locals` object which allows a component to trigger the page to 404 (or any error code....?)

**Comment by nelsonpecora** [comment]
This needs discussion

**Comment by jonwinton** [comment]
This functionality would be very necessary when [dynamic routes](https://github.com/clay/amphora/pull/542) are a thing because we could get a lot of 200's for pages with no good data.

That being said, I want this discussion to be a thing so I did the work to prove it out: https://github.com/clay/amphora/pull/543/files

**Comment by jonwinton** [comment]
To test, that PR passes a function is as a 4th argument to a model's render function.

```javascript
module.exports.render = function (ref, data, locals, errCmpt) {
return errCmpt(404, 'No results');
}
```

It would just be invoked like that. Wouldn't mind attaching it to locals.

**Comment by cperryk** [comment]
What if we pick it up from an error thrown by the render fnc? Like:

```
module.exports.render = function (ref, data, locals) {
  throw new Error(404);
}
```

**Comment by nelsonpecora** [comment]
I like @cperryk's suggestion, because we should probably be catching errors anyway (and defaulting to returning 500s when there are uncaught code errors in our model.js files)

**Comment by jonwinton** [comment]
@cperryk @nelsonpecora so you'd like to throw an error with the status code as the message, Amphora would take the message and apply that to the status code? Or do you want to provide more context than that? 

And all errors in model.js files already do default to 500. The only way for a component to trigger a 400 is to specify that it's `name` property is `NotFoundError`. We can keep this pattern going and say that if you want to 404 you have to format all your errors in a very specific way (or build a service to do it).

Also, how much information do you think should be sent to the client? How much do you think should be logged?

**Comment by jonwinton** [comment]
What if a component wants to 403 a page?

**Comment by cperryk** [comment]
The signal could be the error message or some other property of the error (like `error.name` or perhaps `error.status`). The value should be a status code. Otherwise we have to declare a set of names that match to status codes. 403 would work the same way.

Another alternative would be to expose the `res` object directly in `locals`. Then people could do whatever they want, including redirects. We wouldn't have to describe any way of doing things beyond accessing `res`.

**Comment by nelsonpecora** [comment]
I like the "formatting your errors" approach. Maybe something like...

```js
var e = new Error('uh oh spaghetti-ohs');

e,status = 404;
throw e;
```

I think the message should be sent to the client, and logged, but that's about it.

**Comment by jonwinton** [comment]
I'm fine for that, it just means that the developer has to understand why and how to format the error that way. Let's see how it plays out.
